name: job_runner
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  args: ^2.3.0
  jmespath: ^2.0.1
  intl: ^0.17.0
  requests: ^4.4.1
  queue: ^3.1.0+1
  ftpconnect: ^1.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
